<?php
/**
 * DO NOT EDIT! Generated by TMProtoCompiler!
 * Date: 2014-09-03 11:36:34
 */

class backend_proto_DeleteMonitorHeader extends TMProtoMessage
{
    public $protoId = null;

    public $moduleType = null;

    public $ip = null;

    public static function descriptor()
    {
        $descriptor = new TMProtoDescriptor(__CLASS__);

        $f = new TMProtoField();
        $f->number     = 1;
        $f->name       = 'protoId';
        $f->type       = TMProto::TYPE_UINT32;
        $f->rule       = TMProto::RULE_REQUIRED;
        $descriptor->addField($f);

        $f = new TMProtoField();
        $f->number     = 2;
        $f->name       = 'moduleType';
        $f->type       = TMProto::TYPE_UINT8;
        $f->rule       = TMProto::RULE_REQUIRED;
        $descriptor->addField($f);

        $f = new TMProtoField();
        $f->number     = 3;
        $f->name       = 'ip';
        $f->type       = TMProto::TYPE_UINT32;
        $f->rule       = TMProto::RULE_REQUIRED;
        $descriptor->addField($f);

        return $descriptor;
    }

    public function hasProtoId()
    {
        return $this->has(1);
    }
    
    public function clearProtoId()
    {
        return $this->clear(1);
    }
    
    public function getProtoId()
    {
        return $this->get(1);
    }
    
    public function setProtoId($value)
    {
        return $this->set(1, $value);
    }
    
    public function hasModuleType()
    {
        return $this->has(2);
    }
    
    public function clearModuleType()
    {
        return $this->clear(2);
    }
    
    public function getModuleType()
    {
        return $this->get(2);
    }
    
    public function setModuleType($value)
    {
        return $this->set(2, $value);
    }
    
    public function hasIp()
    {
        return $this->has(3);
    }
    
    public function clearIp()
    {
        return $this->clear(3);
    }
    
    public function getIp()
    {
        return $this->get(3);
    }
    
    public function setIp($value)
    {
        return $this->set(3, $value);
    }
    
}
