// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app_pull_msg.proto

package stat_app_proto;

public final class AppPullMsg {
  private AppPullMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MsgBodyOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string msg_id = 1;
    /**
     * <code>required string msg_id = 1;</code>
     */
    boolean hasMsgId();
    /**
     * <code>required string msg_id = 1;</code>
     */
    java.lang.String getMsgId();
    /**
     * <code>required string msg_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getMsgIdBytes();

    // required string title = 2;
    /**
     * <code>required string title = 2;</code>
     */
    boolean hasTitle();
    /**
     * <code>required string title = 2;</code>
     */
    java.lang.String getTitle();
    /**
     * <code>required string title = 2;</code>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    // required string content = 3;
    /**
     * <code>required string content = 3;</code>
     */
    boolean hasContent();
    /**
     * <code>required string content = 3;</code>
     */
    java.lang.String getContent();
    /**
     * <code>required string content = 3;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();
  }
  /**
   * Protobuf type {@code StatPullMsgProto.MsgBody}
   */
  public static final class MsgBody extends
      com.google.protobuf.GeneratedMessage
      implements MsgBodyOrBuilder {
    // Use MsgBody.newBuilder() to construct.
    private MsgBody(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MsgBody(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MsgBody defaultInstance;
    public static MsgBody getDefaultInstance() {
      return defaultInstance;
    }

    public MsgBody getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MsgBody(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              msgId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              title_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              content_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return stat_app_proto.AppPullMsg.internal_static_StatPullMsgProto_MsgBody_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return stat_app_proto.AppPullMsg.internal_static_StatPullMsgProto_MsgBody_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              stat_app_proto.AppPullMsg.MsgBody.class, stat_app_proto.AppPullMsg.MsgBody.Builder.class);
    }

    public static com.google.protobuf.Parser<MsgBody> PARSER =
        new com.google.protobuf.AbstractParser<MsgBody>() {
      public MsgBody parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MsgBody(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MsgBody> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string msg_id = 1;
    public static final int MSG_ID_FIELD_NUMBER = 1;
    private java.lang.Object msgId_;
    /**
     * <code>required string msg_id = 1;</code>
     */
    public boolean hasMsgId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string msg_id = 1;</code>
     */
    public java.lang.String getMsgId() {
      java.lang.Object ref = msgId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msgId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string msg_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMsgIdBytes() {
      java.lang.Object ref = msgId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string title = 2;
    public static final int TITLE_FIELD_NUMBER = 2;
    private java.lang.Object title_;
    /**
     * <code>required string title = 2;</code>
     */
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string title = 2;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          title_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string title = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string content = 3;
    public static final int CONTENT_FIELD_NUMBER = 3;
    private java.lang.Object content_;
    /**
     * <code>required string content = 3;</code>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string content = 3;</code>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          content_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string content = 3;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      msgId_ = "";
      title_ = "";
      content_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasMsgId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTitle()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getMsgIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTitleBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getContentBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getMsgIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTitleBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getContentBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static stat_app_proto.AppPullMsg.MsgBody parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static stat_app_proto.AppPullMsg.MsgBody parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static stat_app_proto.AppPullMsg.MsgBody parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static stat_app_proto.AppPullMsg.MsgBody parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static stat_app_proto.AppPullMsg.MsgBody parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static stat_app_proto.AppPullMsg.MsgBody parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static stat_app_proto.AppPullMsg.MsgBody parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static stat_app_proto.AppPullMsg.MsgBody parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static stat_app_proto.AppPullMsg.MsgBody parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static stat_app_proto.AppPullMsg.MsgBody parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(stat_app_proto.AppPullMsg.MsgBody prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code StatPullMsgProto.MsgBody}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements stat_app_proto.AppPullMsg.MsgBodyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return stat_app_proto.AppPullMsg.internal_static_StatPullMsgProto_MsgBody_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return stat_app_proto.AppPullMsg.internal_static_StatPullMsgProto_MsgBody_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                stat_app_proto.AppPullMsg.MsgBody.class, stat_app_proto.AppPullMsg.MsgBody.Builder.class);
      }

      // Construct using stat_app_proto.AppPullMsg.MsgBody.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        msgId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        content_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return stat_app_proto.AppPullMsg.internal_static_StatPullMsgProto_MsgBody_descriptor;
      }

      public stat_app_proto.AppPullMsg.MsgBody getDefaultInstanceForType() {
        return stat_app_proto.AppPullMsg.MsgBody.getDefaultInstance();
      }

      public stat_app_proto.AppPullMsg.MsgBody build() {
        stat_app_proto.AppPullMsg.MsgBody result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public stat_app_proto.AppPullMsg.MsgBody buildPartial() {
        stat_app_proto.AppPullMsg.MsgBody result = new stat_app_proto.AppPullMsg.MsgBody(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgId_ = msgId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.content_ = content_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof stat_app_proto.AppPullMsg.MsgBody) {
          return mergeFrom((stat_app_proto.AppPullMsg.MsgBody)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(stat_app_proto.AppPullMsg.MsgBody other) {
        if (other == stat_app_proto.AppPullMsg.MsgBody.getDefaultInstance()) return this;
        if (other.hasMsgId()) {
          bitField0_ |= 0x00000001;
          msgId_ = other.msgId_;
          onChanged();
        }
        if (other.hasTitle()) {
          bitField0_ |= 0x00000002;
          title_ = other.title_;
          onChanged();
        }
        if (other.hasContent()) {
          bitField0_ |= 0x00000004;
          content_ = other.content_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMsgId()) {
          
          return false;
        }
        if (!hasTitle()) {
          
          return false;
        }
        if (!hasContent()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        stat_app_proto.AppPullMsg.MsgBody parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (stat_app_proto.AppPullMsg.MsgBody) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string msg_id = 1;
      private java.lang.Object msgId_ = "";
      /**
       * <code>required string msg_id = 1;</code>
       */
      public boolean hasMsgId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string msg_id = 1;</code>
       */
      public java.lang.String getMsgId() {
        java.lang.Object ref = msgId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          msgId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string msg_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMsgIdBytes() {
        java.lang.Object ref = msgId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string msg_id = 1;</code>
       */
      public Builder setMsgId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string msg_id = 1;</code>
       */
      public Builder clearMsgId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgId_ = getDefaultInstance().getMsgId();
        onChanged();
        return this;
      }
      /**
       * <code>required string msg_id = 1;</code>
       */
      public Builder setMsgIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        msgId_ = value;
        onChanged();
        return this;
      }

      // required string title = 2;
      private java.lang.Object title_ = "";
      /**
       * <code>required string title = 2;</code>
       */
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string title = 2;</code>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string title = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string title = 2;</code>
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string title = 2;</code>
       */
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000002);
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>required string title = 2;</code>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        title_ = value;
        onChanged();
        return this;
      }

      // required string content = 3;
      private java.lang.Object content_ = "";
      /**
       * <code>required string content = 3;</code>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string content = 3;</code>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string content = 3;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string content = 3;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string content = 3;</code>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000004);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>required string content = 3;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        content_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:StatPullMsgProto.MsgBody)
    }

    static {
      defaultInstance = new MsgBody(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:StatPullMsgProto.MsgBody)
  }

  public interface AppPullMsgRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string user_name = 1;
    /**
     * <code>required string user_name = 1;</code>
     */
    boolean hasUserName();
    /**
     * <code>required string user_name = 1;</code>
     */
    java.lang.String getUserName();
    /**
     * <code>required string user_name = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    // repeated string msg_id = 2;
    /**
     * <code>repeated string msg_id = 2;</code>
     */
    java.util.List<java.lang.String>
    getMsgIdList();
    /**
     * <code>repeated string msg_id = 2;</code>
     */
    int getMsgIdCount();
    /**
     * <code>repeated string msg_id = 2;</code>
     */
    java.lang.String getMsgId(int index);
    /**
     * <code>repeated string msg_id = 2;</code>
     */
    com.google.protobuf.ByteString
        getMsgIdBytes(int index);

    // optional string token = 3;
    /**
     * <code>optional string token = 3;</code>
     */
    boolean hasToken();
    /**
     * <code>optional string token = 3;</code>
     */
    java.lang.String getToken();
    /**
     * <code>optional string token = 3;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes();
  }
  /**
   * Protobuf type {@code StatPullMsgProto.AppPullMsgRequest}
   */
  public static final class AppPullMsgRequest extends
      com.google.protobuf.GeneratedMessage
      implements AppPullMsgRequestOrBuilder {
    // Use AppPullMsgRequest.newBuilder() to construct.
    private AppPullMsgRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AppPullMsgRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AppPullMsgRequest defaultInstance;
    public static AppPullMsgRequest getDefaultInstance() {
      return defaultInstance;
    }

    public AppPullMsgRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AppPullMsgRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              userName_ = input.readBytes();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                msgId_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              msgId_.add(input.readBytes());
              break;
            }
            case 26: {
              bitField0_ |= 0x00000002;
              token_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          msgId_ = new com.google.protobuf.UnmodifiableLazyStringList(msgId_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return stat_app_proto.AppPullMsg.internal_static_StatPullMsgProto_AppPullMsgRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return stat_app_proto.AppPullMsg.internal_static_StatPullMsgProto_AppPullMsgRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              stat_app_proto.AppPullMsg.AppPullMsgRequest.class, stat_app_proto.AppPullMsg.AppPullMsgRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<AppPullMsgRequest> PARSER =
        new com.google.protobuf.AbstractParser<AppPullMsgRequest>() {
      public AppPullMsgRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AppPullMsgRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AppPullMsgRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string user_name = 1;
    public static final int USER_NAME_FIELD_NUMBER = 1;
    private java.lang.Object userName_;
    /**
     * <code>required string user_name = 1;</code>
     */
    public boolean hasUserName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string user_name = 1;</code>
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string user_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated string msg_id = 2;
    public static final int MSG_ID_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList msgId_;
    /**
     * <code>repeated string msg_id = 2;</code>
     */
    public java.util.List<java.lang.String>
        getMsgIdList() {
      return msgId_;
    }
    /**
     * <code>repeated string msg_id = 2;</code>
     */
    public int getMsgIdCount() {
      return msgId_.size();
    }
    /**
     * <code>repeated string msg_id = 2;</code>
     */
    public java.lang.String getMsgId(int index) {
      return msgId_.get(index);
    }
    /**
     * <code>repeated string msg_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMsgIdBytes(int index) {
      return msgId_.getByteString(index);
    }

    // optional string token = 3;
    public static final int TOKEN_FIELD_NUMBER = 3;
    private java.lang.Object token_;
    /**
     * <code>optional string token = 3;</code>
     */
    public boolean hasToken() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string token = 3;</code>
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          token_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string token = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      userName_ = "";
      msgId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      token_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUserName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUserNameBytes());
      }
      for (int i = 0; i < msgId_.size(); i++) {
        output.writeBytes(2, msgId_.getByteString(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(3, getTokenBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUserNameBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < msgId_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(msgId_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getMsgIdList().size();
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTokenBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static stat_app_proto.AppPullMsg.AppPullMsgRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static stat_app_proto.AppPullMsg.AppPullMsgRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static stat_app_proto.AppPullMsg.AppPullMsgRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static stat_app_proto.AppPullMsg.AppPullMsgRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static stat_app_proto.AppPullMsg.AppPullMsgRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static stat_app_proto.AppPullMsg.AppPullMsgRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static stat_app_proto.AppPullMsg.AppPullMsgRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static stat_app_proto.AppPullMsg.AppPullMsgRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static stat_app_proto.AppPullMsg.AppPullMsgRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static stat_app_proto.AppPullMsg.AppPullMsgRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(stat_app_proto.AppPullMsg.AppPullMsgRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code StatPullMsgProto.AppPullMsgRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements stat_app_proto.AppPullMsg.AppPullMsgRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return stat_app_proto.AppPullMsg.internal_static_StatPullMsgProto_AppPullMsgRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return stat_app_proto.AppPullMsg.internal_static_StatPullMsgProto_AppPullMsgRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                stat_app_proto.AppPullMsg.AppPullMsgRequest.class, stat_app_proto.AppPullMsg.AppPullMsgRequest.Builder.class);
      }

      // Construct using stat_app_proto.AppPullMsg.AppPullMsgRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        msgId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        token_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return stat_app_proto.AppPullMsg.internal_static_StatPullMsgProto_AppPullMsgRequest_descriptor;
      }

      public stat_app_proto.AppPullMsg.AppPullMsgRequest getDefaultInstanceForType() {
        return stat_app_proto.AppPullMsg.AppPullMsgRequest.getDefaultInstance();
      }

      public stat_app_proto.AppPullMsg.AppPullMsgRequest build() {
        stat_app_proto.AppPullMsg.AppPullMsgRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public stat_app_proto.AppPullMsg.AppPullMsgRequest buildPartial() {
        stat_app_proto.AppPullMsg.AppPullMsgRequest result = new stat_app_proto.AppPullMsg.AppPullMsgRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userName_ = userName_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          msgId_ = new com.google.protobuf.UnmodifiableLazyStringList(
              msgId_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.msgId_ = msgId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.token_ = token_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof stat_app_proto.AppPullMsg.AppPullMsgRequest) {
          return mergeFrom((stat_app_proto.AppPullMsg.AppPullMsgRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(stat_app_proto.AppPullMsg.AppPullMsgRequest other) {
        if (other == stat_app_proto.AppPullMsg.AppPullMsgRequest.getDefaultInstance()) return this;
        if (other.hasUserName()) {
          bitField0_ |= 0x00000001;
          userName_ = other.userName_;
          onChanged();
        }
        if (!other.msgId_.isEmpty()) {
          if (msgId_.isEmpty()) {
            msgId_ = other.msgId_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureMsgIdIsMutable();
            msgId_.addAll(other.msgId_);
          }
          onChanged();
        }
        if (other.hasToken()) {
          bitField0_ |= 0x00000004;
          token_ = other.token_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        stat_app_proto.AppPullMsg.AppPullMsgRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (stat_app_proto.AppPullMsg.AppPullMsgRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string user_name = 1;
      private java.lang.Object userName_ = "";
      /**
       * <code>required string user_name = 1;</code>
       */
      public boolean hasUserName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string user_name = 1;</code>
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string user_name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string user_name = 1;</code>
       */
      public Builder setUserName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string user_name = 1;</code>
       */
      public Builder clearUserName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <code>required string user_name = 1;</code>
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userName_ = value;
        onChanged();
        return this;
      }

      // repeated string msg_id = 2;
      private com.google.protobuf.LazyStringList msgId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureMsgIdIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          msgId_ = new com.google.protobuf.LazyStringArrayList(msgId_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string msg_id = 2;</code>
       */
      public java.util.List<java.lang.String>
          getMsgIdList() {
        return java.util.Collections.unmodifiableList(msgId_);
      }
      /**
       * <code>repeated string msg_id = 2;</code>
       */
      public int getMsgIdCount() {
        return msgId_.size();
      }
      /**
       * <code>repeated string msg_id = 2;</code>
       */
      public java.lang.String getMsgId(int index) {
        return msgId_.get(index);
      }
      /**
       * <code>repeated string msg_id = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMsgIdBytes(int index) {
        return msgId_.getByteString(index);
      }
      /**
       * <code>repeated string msg_id = 2;</code>
       */
      public Builder setMsgId(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMsgIdIsMutable();
        msgId_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string msg_id = 2;</code>
       */
      public Builder addMsgId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMsgIdIsMutable();
        msgId_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string msg_id = 2;</code>
       */
      public Builder addAllMsgId(
          java.lang.Iterable<java.lang.String> values) {
        ensureMsgIdIsMutable();
        super.addAll(values, msgId_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string msg_id = 2;</code>
       */
      public Builder clearMsgId() {
        msgId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string msg_id = 2;</code>
       */
      public Builder addMsgIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMsgIdIsMutable();
        msgId_.add(value);
        onChanged();
        return this;
      }

      // optional string token = 3;
      private java.lang.Object token_ = "";
      /**
       * <code>optional string token = 3;</code>
       */
      public boolean hasToken() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string token = 3;</code>
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string token = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string token = 3;</code>
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string token = 3;</code>
       */
      public Builder clearToken() {
        bitField0_ = (bitField0_ & ~0x00000004);
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>optional string token = 3;</code>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        token_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:StatPullMsgProto.AppPullMsgRequest)
    }

    static {
      defaultInstance = new AppPullMsgRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:StatPullMsgProto.AppPullMsgRequest)
  }

  public interface AppPullMsgResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required uint32 ret = 1;
    /**
     * <code>required uint32 ret = 1;</code>
     *
     * <pre>
     * 0:Success, 1:Error, 2:Response by push, 3:Just has msg_id
     * </pre>
     */
    boolean hasRet();
    /**
     * <code>required uint32 ret = 1;</code>
     *
     * <pre>
     * 0:Success, 1:Error, 2:Response by push, 3:Just has msg_id
     * </pre>
     */
    int getRet();

    // repeated .StatPullMsgProto.MsgBody msg = 2;
    /**
     * <code>repeated .StatPullMsgProto.MsgBody msg = 2;</code>
     */
    java.util.List<stat_app_proto.AppPullMsg.MsgBody> 
        getMsgList();
    /**
     * <code>repeated .StatPullMsgProto.MsgBody msg = 2;</code>
     */
    stat_app_proto.AppPullMsg.MsgBody getMsg(int index);
    /**
     * <code>repeated .StatPullMsgProto.MsgBody msg = 2;</code>
     */
    int getMsgCount();
    /**
     * <code>repeated .StatPullMsgProto.MsgBody msg = 2;</code>
     */
    java.util.List<? extends stat_app_proto.AppPullMsg.MsgBodyOrBuilder> 
        getMsgOrBuilderList();
    /**
     * <code>repeated .StatPullMsgProto.MsgBody msg = 2;</code>
     */
    stat_app_proto.AppPullMsg.MsgBodyOrBuilder getMsgOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code StatPullMsgProto.AppPullMsgResponse}
   */
  public static final class AppPullMsgResponse extends
      com.google.protobuf.GeneratedMessage
      implements AppPullMsgResponseOrBuilder {
    // Use AppPullMsgResponse.newBuilder() to construct.
    private AppPullMsgResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AppPullMsgResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AppPullMsgResponse defaultInstance;
    public static AppPullMsgResponse getDefaultInstance() {
      return defaultInstance;
    }

    public AppPullMsgResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AppPullMsgResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              ret_ = input.readUInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                msg_ = new java.util.ArrayList<stat_app_proto.AppPullMsg.MsgBody>();
                mutable_bitField0_ |= 0x00000002;
              }
              msg_.add(input.readMessage(stat_app_proto.AppPullMsg.MsgBody.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          msg_ = java.util.Collections.unmodifiableList(msg_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return stat_app_proto.AppPullMsg.internal_static_StatPullMsgProto_AppPullMsgResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return stat_app_proto.AppPullMsg.internal_static_StatPullMsgProto_AppPullMsgResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              stat_app_proto.AppPullMsg.AppPullMsgResponse.class, stat_app_proto.AppPullMsg.AppPullMsgResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<AppPullMsgResponse> PARSER =
        new com.google.protobuf.AbstractParser<AppPullMsgResponse>() {
      public AppPullMsgResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AppPullMsgResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AppPullMsgResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required uint32 ret = 1;
    public static final int RET_FIELD_NUMBER = 1;
    private int ret_;
    /**
     * <code>required uint32 ret = 1;</code>
     *
     * <pre>
     * 0:Success, 1:Error, 2:Response by push, 3:Just has msg_id
     * </pre>
     */
    public boolean hasRet() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 ret = 1;</code>
     *
     * <pre>
     * 0:Success, 1:Error, 2:Response by push, 3:Just has msg_id
     * </pre>
     */
    public int getRet() {
      return ret_;
    }

    // repeated .StatPullMsgProto.MsgBody msg = 2;
    public static final int MSG_FIELD_NUMBER = 2;
    private java.util.List<stat_app_proto.AppPullMsg.MsgBody> msg_;
    /**
     * <code>repeated .StatPullMsgProto.MsgBody msg = 2;</code>
     */
    public java.util.List<stat_app_proto.AppPullMsg.MsgBody> getMsgList() {
      return msg_;
    }
    /**
     * <code>repeated .StatPullMsgProto.MsgBody msg = 2;</code>
     */
    public java.util.List<? extends stat_app_proto.AppPullMsg.MsgBodyOrBuilder> 
        getMsgOrBuilderList() {
      return msg_;
    }
    /**
     * <code>repeated .StatPullMsgProto.MsgBody msg = 2;</code>
     */
    public int getMsgCount() {
      return msg_.size();
    }
    /**
     * <code>repeated .StatPullMsgProto.MsgBody msg = 2;</code>
     */
    public stat_app_proto.AppPullMsg.MsgBody getMsg(int index) {
      return msg_.get(index);
    }
    /**
     * <code>repeated .StatPullMsgProto.MsgBody msg = 2;</code>
     */
    public stat_app_proto.AppPullMsg.MsgBodyOrBuilder getMsgOrBuilder(
        int index) {
      return msg_.get(index);
    }

    private void initFields() {
      ret_ = 0;
      msg_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasRet()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getMsgCount(); i++) {
        if (!getMsg(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, ret_);
      }
      for (int i = 0; i < msg_.size(); i++) {
        output.writeMessage(2, msg_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, ret_);
      }
      for (int i = 0; i < msg_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, msg_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static stat_app_proto.AppPullMsg.AppPullMsgResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static stat_app_proto.AppPullMsg.AppPullMsgResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static stat_app_proto.AppPullMsg.AppPullMsgResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static stat_app_proto.AppPullMsg.AppPullMsgResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static stat_app_proto.AppPullMsg.AppPullMsgResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static stat_app_proto.AppPullMsg.AppPullMsgResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static stat_app_proto.AppPullMsg.AppPullMsgResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static stat_app_proto.AppPullMsg.AppPullMsgResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static stat_app_proto.AppPullMsg.AppPullMsgResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static stat_app_proto.AppPullMsg.AppPullMsgResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(stat_app_proto.AppPullMsg.AppPullMsgResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code StatPullMsgProto.AppPullMsgResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements stat_app_proto.AppPullMsg.AppPullMsgResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return stat_app_proto.AppPullMsg.internal_static_StatPullMsgProto_AppPullMsgResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return stat_app_proto.AppPullMsg.internal_static_StatPullMsgProto_AppPullMsgResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                stat_app_proto.AppPullMsg.AppPullMsgResponse.class, stat_app_proto.AppPullMsg.AppPullMsgResponse.Builder.class);
      }

      // Construct using stat_app_proto.AppPullMsg.AppPullMsgResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMsgFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        ret_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (msgBuilder_ == null) {
          msg_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          msgBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return stat_app_proto.AppPullMsg.internal_static_StatPullMsgProto_AppPullMsgResponse_descriptor;
      }

      public stat_app_proto.AppPullMsg.AppPullMsgResponse getDefaultInstanceForType() {
        return stat_app_proto.AppPullMsg.AppPullMsgResponse.getDefaultInstance();
      }

      public stat_app_proto.AppPullMsg.AppPullMsgResponse build() {
        stat_app_proto.AppPullMsg.AppPullMsgResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public stat_app_proto.AppPullMsg.AppPullMsgResponse buildPartial() {
        stat_app_proto.AppPullMsg.AppPullMsgResponse result = new stat_app_proto.AppPullMsg.AppPullMsgResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ret_ = ret_;
        if (msgBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            msg_ = java.util.Collections.unmodifiableList(msg_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.msg_ = msg_;
        } else {
          result.msg_ = msgBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof stat_app_proto.AppPullMsg.AppPullMsgResponse) {
          return mergeFrom((stat_app_proto.AppPullMsg.AppPullMsgResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(stat_app_proto.AppPullMsg.AppPullMsgResponse other) {
        if (other == stat_app_proto.AppPullMsg.AppPullMsgResponse.getDefaultInstance()) return this;
        if (other.hasRet()) {
          setRet(other.getRet());
        }
        if (msgBuilder_ == null) {
          if (!other.msg_.isEmpty()) {
            if (msg_.isEmpty()) {
              msg_ = other.msg_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureMsgIsMutable();
              msg_.addAll(other.msg_);
            }
            onChanged();
          }
        } else {
          if (!other.msg_.isEmpty()) {
            if (msgBuilder_.isEmpty()) {
              msgBuilder_.dispose();
              msgBuilder_ = null;
              msg_ = other.msg_;
              bitField0_ = (bitField0_ & ~0x00000002);
              msgBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMsgFieldBuilder() : null;
            } else {
              msgBuilder_.addAllMessages(other.msg_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRet()) {
          
          return false;
        }
        for (int i = 0; i < getMsgCount(); i++) {
          if (!getMsg(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        stat_app_proto.AppPullMsg.AppPullMsgResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (stat_app_proto.AppPullMsg.AppPullMsgResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required uint32 ret = 1;
      private int ret_ ;
      /**
       * <code>required uint32 ret = 1;</code>
       *
       * <pre>
       * 0:Success, 1:Error, 2:Response by push, 3:Just has msg_id
       * </pre>
       */
      public boolean hasRet() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 ret = 1;</code>
       *
       * <pre>
       * 0:Success, 1:Error, 2:Response by push, 3:Just has msg_id
       * </pre>
       */
      public int getRet() {
        return ret_;
      }
      /**
       * <code>required uint32 ret = 1;</code>
       *
       * <pre>
       * 0:Success, 1:Error, 2:Response by push, 3:Just has msg_id
       * </pre>
       */
      public Builder setRet(int value) {
        bitField0_ |= 0x00000001;
        ret_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 ret = 1;</code>
       *
       * <pre>
       * 0:Success, 1:Error, 2:Response by push, 3:Just has msg_id
       * </pre>
       */
      public Builder clearRet() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ret_ = 0;
        onChanged();
        return this;
      }

      // repeated .StatPullMsgProto.MsgBody msg = 2;
      private java.util.List<stat_app_proto.AppPullMsg.MsgBody> msg_ =
        java.util.Collections.emptyList();
      private void ensureMsgIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          msg_ = new java.util.ArrayList<stat_app_proto.AppPullMsg.MsgBody>(msg_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          stat_app_proto.AppPullMsg.MsgBody, stat_app_proto.AppPullMsg.MsgBody.Builder, stat_app_proto.AppPullMsg.MsgBodyOrBuilder> msgBuilder_;

      /**
       * <code>repeated .StatPullMsgProto.MsgBody msg = 2;</code>
       */
      public java.util.List<stat_app_proto.AppPullMsg.MsgBody> getMsgList() {
        if (msgBuilder_ == null) {
          return java.util.Collections.unmodifiableList(msg_);
        } else {
          return msgBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .StatPullMsgProto.MsgBody msg = 2;</code>
       */
      public int getMsgCount() {
        if (msgBuilder_ == null) {
          return msg_.size();
        } else {
          return msgBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .StatPullMsgProto.MsgBody msg = 2;</code>
       */
      public stat_app_proto.AppPullMsg.MsgBody getMsg(int index) {
        if (msgBuilder_ == null) {
          return msg_.get(index);
        } else {
          return msgBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .StatPullMsgProto.MsgBody msg = 2;</code>
       */
      public Builder setMsg(
          int index, stat_app_proto.AppPullMsg.MsgBody value) {
        if (msgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMsgIsMutable();
          msg_.set(index, value);
          onChanged();
        } else {
          msgBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .StatPullMsgProto.MsgBody msg = 2;</code>
       */
      public Builder setMsg(
          int index, stat_app_proto.AppPullMsg.MsgBody.Builder builderForValue) {
        if (msgBuilder_ == null) {
          ensureMsgIsMutable();
          msg_.set(index, builderForValue.build());
          onChanged();
        } else {
          msgBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .StatPullMsgProto.MsgBody msg = 2;</code>
       */
      public Builder addMsg(stat_app_proto.AppPullMsg.MsgBody value) {
        if (msgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMsgIsMutable();
          msg_.add(value);
          onChanged();
        } else {
          msgBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .StatPullMsgProto.MsgBody msg = 2;</code>
       */
      public Builder addMsg(
          int index, stat_app_proto.AppPullMsg.MsgBody value) {
        if (msgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMsgIsMutable();
          msg_.add(index, value);
          onChanged();
        } else {
          msgBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .StatPullMsgProto.MsgBody msg = 2;</code>
       */
      public Builder addMsg(
          stat_app_proto.AppPullMsg.MsgBody.Builder builderForValue) {
        if (msgBuilder_ == null) {
          ensureMsgIsMutable();
          msg_.add(builderForValue.build());
          onChanged();
        } else {
          msgBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .StatPullMsgProto.MsgBody msg = 2;</code>
       */
      public Builder addMsg(
          int index, stat_app_proto.AppPullMsg.MsgBody.Builder builderForValue) {
        if (msgBuilder_ == null) {
          ensureMsgIsMutable();
          msg_.add(index, builderForValue.build());
          onChanged();
        } else {
          msgBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .StatPullMsgProto.MsgBody msg = 2;</code>
       */
      public Builder addAllMsg(
          java.lang.Iterable<? extends stat_app_proto.AppPullMsg.MsgBody> values) {
        if (msgBuilder_ == null) {
          ensureMsgIsMutable();
          super.addAll(values, msg_);
          onChanged();
        } else {
          msgBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .StatPullMsgProto.MsgBody msg = 2;</code>
       */
      public Builder clearMsg() {
        if (msgBuilder_ == null) {
          msg_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          msgBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .StatPullMsgProto.MsgBody msg = 2;</code>
       */
      public Builder removeMsg(int index) {
        if (msgBuilder_ == null) {
          ensureMsgIsMutable();
          msg_.remove(index);
          onChanged();
        } else {
          msgBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .StatPullMsgProto.MsgBody msg = 2;</code>
       */
      public stat_app_proto.AppPullMsg.MsgBody.Builder getMsgBuilder(
          int index) {
        return getMsgFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .StatPullMsgProto.MsgBody msg = 2;</code>
       */
      public stat_app_proto.AppPullMsg.MsgBodyOrBuilder getMsgOrBuilder(
          int index) {
        if (msgBuilder_ == null) {
          return msg_.get(index);  } else {
          return msgBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .StatPullMsgProto.MsgBody msg = 2;</code>
       */
      public java.util.List<? extends stat_app_proto.AppPullMsg.MsgBodyOrBuilder> 
           getMsgOrBuilderList() {
        if (msgBuilder_ != null) {
          return msgBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(msg_);
        }
      }
      /**
       * <code>repeated .StatPullMsgProto.MsgBody msg = 2;</code>
       */
      public stat_app_proto.AppPullMsg.MsgBody.Builder addMsgBuilder() {
        return getMsgFieldBuilder().addBuilder(
            stat_app_proto.AppPullMsg.MsgBody.getDefaultInstance());
      }
      /**
       * <code>repeated .StatPullMsgProto.MsgBody msg = 2;</code>
       */
      public stat_app_proto.AppPullMsg.MsgBody.Builder addMsgBuilder(
          int index) {
        return getMsgFieldBuilder().addBuilder(
            index, stat_app_proto.AppPullMsg.MsgBody.getDefaultInstance());
      }
      /**
       * <code>repeated .StatPullMsgProto.MsgBody msg = 2;</code>
       */
      public java.util.List<stat_app_proto.AppPullMsg.MsgBody.Builder> 
           getMsgBuilderList() {
        return getMsgFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          stat_app_proto.AppPullMsg.MsgBody, stat_app_proto.AppPullMsg.MsgBody.Builder, stat_app_proto.AppPullMsg.MsgBodyOrBuilder> 
          getMsgFieldBuilder() {
        if (msgBuilder_ == null) {
          msgBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              stat_app_proto.AppPullMsg.MsgBody, stat_app_proto.AppPullMsg.MsgBody.Builder, stat_app_proto.AppPullMsg.MsgBodyOrBuilder>(
                  msg_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          msg_ = null;
        }
        return msgBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:StatPullMsgProto.AppPullMsgResponse)
    }

    static {
      defaultInstance = new AppPullMsgResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:StatPullMsgProto.AppPullMsgResponse)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_StatPullMsgProto_MsgBody_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_StatPullMsgProto_MsgBody_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_StatPullMsgProto_AppPullMsgRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_StatPullMsgProto_AppPullMsgRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_StatPullMsgProto_AppPullMsgResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_StatPullMsgProto_AppPullMsgResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022app_pull_msg.proto\022\020StatPullMsgProto\"9" +
      "\n\007MsgBody\022\016\n\006msg_id\030\001 \002(\t\022\r\n\005title\030\002 \002(\t" +
      "\022\017\n\007content\030\003 \002(\t\"E\n\021AppPullMsgRequest\022\021" +
      "\n\tuser_name\030\001 \002(\t\022\016\n\006msg_id\030\002 \003(\t\022\r\n\005tok" +
      "en\030\003 \001(\t\"I\n\022AppPullMsgResponse\022\013\n\003ret\030\001 " +
      "\002(\r\022&\n\003msg\030\002 \003(\0132\031.StatPullMsgProto.MsgB" +
      "odyB\020\n\016stat_app_proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_StatPullMsgProto_MsgBody_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_StatPullMsgProto_MsgBody_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_StatPullMsgProto_MsgBody_descriptor,
              new java.lang.String[] { "MsgId", "Title", "Content", });
          internal_static_StatPullMsgProto_AppPullMsgRequest_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_StatPullMsgProto_AppPullMsgRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_StatPullMsgProto_AppPullMsgRequest_descriptor,
              new java.lang.String[] { "UserName", "MsgId", "Token", });
          internal_static_StatPullMsgProto_AppPullMsgResponse_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_StatPullMsgProto_AppPullMsgResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_StatPullMsgProto_AppPullMsgResponse_descriptor,
              new java.lang.String[] { "Ret", "Msg", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
