<?php
/**
 * DO NOT EDIT! Generated by TMProtoCompiler!
 * Date: 2014-09-03 11:36:34
 */

class backend_proto_GetHeader extends TMProtoMessage
{
    public $protoId = null;

    public $moduleType = null;

    public $printType = 1;

    public $printFlag = null;

    public $ip = 0;

    public static function descriptor()
    {
        $descriptor = new TMProtoDescriptor(__CLASS__);

        $f = new TMProtoField();
        $f->number     = 1;
        $f->name       = 'protoId';
        $f->type       = TMProto::TYPE_UINT32;
        $f->rule       = TMProto::RULE_REQUIRED;
        $descriptor->addField($f);

        $f = new TMProtoField();
        $f->number     = 2;
        $f->name       = 'moduleType';
        $f->type       = TMProto::TYPE_UINT8;
        $f->rule       = TMProto::RULE_REQUIRED;
        $descriptor->addField($f);

        $f = new TMProtoField();
        $f->number     = 3;
        $f->name       = 'printType';
        $f->type       = TMProto::TYPE_UINT8;
        $f->rule       = TMProto::RULE_REQUIRED;
        $f->default    = 1;
        $descriptor->addField($f);

        $f = new TMProtoField();
        $f->number     = 4;
        $f->name       = 'printFlag';
        $f->type       = TMProto::TYPE_UINT8;
        $f->rule       = TMProto::RULE_REQUIRED;
        $descriptor->addField($f);

        $f = new TMProtoField();
        $f->number     = 5;
        $f->name       = 'ip';
        $f->type       = TMProto::TYPE_UINT32;
        $f->rule       = TMProto::RULE_REQUIRED;
        $f->default    = 0;
        $descriptor->addField($f);

        return $descriptor;
    }

    public function hasProtoId()
    {
        return $this->has(1);
    }
    
    public function clearProtoId()
    {
        return $this->clear(1);
    }
    
    public function getProtoId()
    {
        return $this->get(1);
    }
    
    public function setProtoId($value)
    {
        return $this->set(1, $value);
    }
    
    public function hasModuleType()
    {
        return $this->has(2);
    }
    
    public function clearModuleType()
    {
        return $this->clear(2);
    }
    
    public function getModuleType()
    {
        return $this->get(2);
    }
    
    public function setModuleType($value)
    {
        return $this->set(2, $value);
    }
    
    public function hasPrintType()
    {
        return $this->has(3);
    }
    
    public function clearPrintType()
    {
        return $this->clear(3);
    }
    
    public function getPrintType()
    {
        return $this->get(3);
    }
    
    public function setPrintType($value)
    {
        return $this->set(3, $value);
    }
    
    public function hasPrintFlag()
    {
        return $this->has(4);
    }
    
    public function clearPrintFlag()
    {
        return $this->clear(4);
    }
    
    public function getPrintFlag()
    {
        return $this->get(4);
    }
    
    public function setPrintFlag($value)
    {
        return $this->set(4, $value);
    }
    
    public function hasIp()
    {
        return $this->has(5);
    }
    
    public function clearIp()
    {
        return $this->clear(5);
    }
    
    public function getIp()
    {
        return $this->get(5);
    }
    
    public function setIp($value)
    {
        return $this->set(5, $value);
    }
    
}
