<?php
/**
 * DO NOT EDIT! Generated by TMProtoCompiler!
 * Date: 2014-09-03 11:36:34
 */

class backend_proto_ResponseHeader extends TMProtoMessage
{
    public $protoId = null;

    public $code = null;

    public static function descriptor()
    {
        $descriptor = new TMProtoDescriptor(__CLASS__);

        $f = new TMProtoField();
        $f->number     = 1;
        $f->name       = 'protoId';
        $f->type       = TMProto::TYPE_UINT32;
        $f->rule       = TMProto::RULE_REQUIRED;
        $descriptor->addField($f);

        $f = new TMProtoField();
        $f->number     = 2;
        $f->name       = 'code';
        $f->type       = TMProto::TYPE_INT8;
        $f->rule       = TMProto::RULE_REQUIRED;
        $descriptor->addField($f);

        return $descriptor;
    }

    public function hasProtoId()
    {
        return $this->has(1);
    }
    
    public function clearProtoId()
    {
        return $this->clear(1);
    }
    
    public function getProtoId()
    {
        return $this->get(1);
    }
    
    public function setProtoId($value)
    {
        return $this->set(1, $value);
    }
    
    public function hasCode()
    {
        return $this->has(2);
    }
    
    public function clearCode()
    {
        return $this->clear(2);
    }
    
    public function getCode()
    {
        return $this->get(2);
    }
    
    public function setCode($value)
    {
        return $this->set(2, $value);
    }
    
}
